# Funding links for this repository. Renders as a "Sponsor" button on GitHub.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [mdostal]
buy_me_a_coffee: mdostal
