// Pure read layer over .pHive/ state: epics, story YAMLs, post-run audit
// records, and recent git log. Plain functions, no classes (matches this
// codebase's convention everywhere else — see
// src/router/lib/adapters/multica/backlog.mjs). Every function here is
// SYNCHRONOUS (fs.*Sync, execFileSync) — matches this codebase's established
// synchronous-CLI-wrapper convention (cli-runner.mjs's makeRun()); no
// async/Promise machinery is introduced because nothing here is genuinely
// asynchronous (local file reads, a single git subprocess call).
//
// Read-only, permanently: this module exposes no write/mutate functions at
// all — v1 is display-only by explicit design decision (see
// .pHive/epics/p3-auriga-ui/docs/design-discussion.md §1/§3), not an
// oversight to "fix" later.
//
// Every per-file read (one epic.yaml, one story yaml, one audit yaml) is
// wrapped in its own try/catch: a single malformed or unreadable file is
// skipped (with a stderr log, matching backlog.mjs's
// `process.stderr.write(...failed: ...)` convention) and never aborts the
// rest of a listing. This is the story's explicit, non-negotiable acceptance
// criterion, not a nice-to-have.

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// lib/ -> server/ -> src/ -> repo root
export const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
export const DEFAULT_PHIVE_ROOT = path.join(REPO_ROOT, '.pHive');

// YAML parsing is delegated entirely to the `yaml` package (this server's
// first real runtime dependency, deliberately — see package.json's
// description). A prior version of this file hand-rolled a minimal parser
// for the subset of YAML this repo's own .pHive/ files happened to use;
// that was replaced because future story YAMLs (generated by /plan) can
// have more complex shapes than what the hand-rolled parser was verified
// against, and a subtle mis-parse would silently corrupt what the dashboard
// displays. `yaml`'s parse() throws a YAMLParseError (a real, well-defined
// error) on genuinely malformed input, which every call site below catches
// per-file — same graceful-degradation contract as before, just backed by a
// real parser instead of a hand-rolled one.

// ---------------------------------------------------------------------------
// File loaders — each wraps fs.readFileSync + parseYaml + minimal required-
// field validation in a single throwable unit, so every call site can catch
// exactly one error and skip-with-a-log per file.
// ---------------------------------------------------------------------------

function readEpicYaml(epicDir) {
  const raw = fs.readFileSync(path.join(epicDir, 'epic.yaml'), 'utf8');
  const parsed = parseYaml(raw);
  if (!parsed || typeof parsed !== 'object' || !parsed.name) {
    throw new Error("epic.yaml missing required 'name' field");
  }
  return parsed;
}

function readStoryYaml(storyPath) {
  const raw = fs.readFileSync(storyPath, 'utf8');
  const parsed = parseYaml(raw);
  if (!parsed || typeof parsed !== 'object' || !parsed.id || !parsed.title) {
    throw new Error("story yaml missing required 'id'/'title' field");
  }
  return parsed;
}

function listStoryFiles(epicDir) {
  try {
    return fs.readdirSync(path.join(epicDir, 'stories'))
      .filter((f) => f.endsWith('.yaml'))
      .map((f) => path.join(epicDir, 'stories', f));
  } catch (e) {
    return [];
  }
}

function deriveEpicStatus(storyStatuses) {
  if (storyStatuses.length === 0) return 'planning';
  if (storyStatuses.every((s) => s === 'done')) return 'done';
  if (storyStatuses.some((s) => s !== 'pending')) return 'in-progress';
  return 'pending';
}

/**
 * [{id, title, status, story_count, docs_path}] built from
 * .pHive/epics/*\/epic.yaml on disk. `status` is a rollup derived from each
 * epic's stories/*.yaml statuses (epic.yaml itself carries no status field —
 * see .pHive/epics/p3-auriga-ui/docs/horizontal-plan.md's "status per story
 * rollup" note): 'done' if every story is done, 'in-progress' if any story
 * has moved off 'pending', 'planning' if the epic has no story files at all,
 * else 'pending'.
 * @param {string} [root] .pHive root — overridable for tests
 * @returns {Array<{id:string,title:string,status:string,story_count:number,docs_path:string}>}
 */
export function listEpics(root = DEFAULT_PHIVE_ROOT) {
  const epicsDir = path.join(root, 'epics');
  let dirEntries = [];
  try {
    dirEntries = fs.readdirSync(epicsDir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name);
  } catch (e) {
    process.stderr.write(`listEpics: cannot read epics dir ${epicsDir}: ${e.message}\n`);
    return [];
  }

  const out = [];
  for (const dirName of dirEntries) {
    const epicDir = path.join(epicsDir, dirName);
    let epic;
    try {
      epic = readEpicYaml(epicDir);
    } catch (e) {
      process.stderr.write(`listEpics: skipping ${dirName}/epic.yaml: ${e.message}\n`);
      continue;
    }

    const storyFiles = listStoryFiles(epicDir);
    const statuses = [];
    for (const storyPath of storyFiles) {
      try {
        const story = readStoryYaml(storyPath);
        statuses.push(String(story.status || 'pending'));
      } catch (e) {
        process.stderr.write(`listEpics: skipping malformed story ${storyPath}: ${e.message}\n`);
      }
    }

    out.push({
      id: epic.name || dirName,
      title: epic.title || epic.name || dirName,
      status: deriveEpicStatus(statuses),
      story_count: storyFiles.length,
      docs_path: path.relative(REPO_ROOT, path.join(epicDir, 'docs')),
    });
  }
  return out;
}

/**
 * One epic's detail: stories[] (id, title, status, complexity, depends_on)
 * and a list of its docs. Returns null if the epic id doesn't exist or its
 * epic.yaml is malformed/unreadable (the caller — index.mjs — turns that
 * into a 404, never a 500).
 * @param {string} id
 * @param {string} [root]
 */
export function getEpic(id, root = DEFAULT_PHIVE_ROOT) {
  const epicDir = path.join(root, 'epics', id);
  let epic;
  try {
    epic = readEpicYaml(epicDir);
  } catch (e) {
    process.stderr.write(`getEpic(${id}): ${e.message}\n`);
    return null;
  }

  const stories = [];
  for (const storyPath of listStoryFiles(epicDir)) {
    try {
      const story = readStoryYaml(storyPath);
      stories.push({
        id: story.id,
        title: story.title,
        status: story.status || 'pending',
        complexity: story.complexity || null,
        depends_on: Array.isArray(story.depends_on) ? story.depends_on : [],
      });
    } catch (e) {
      process.stderr.write(`getEpic(${id}): skipping malformed story ${storyPath}: ${e.message}\n`);
    }
  }

  const docsDir = path.join(epicDir, 'docs');
  let docs = [];
  try {
    docs = fs.readdirSync(docsDir).filter((f) => !f.startsWith('.'));
  } catch (e) {
    docs = [];
  }

  return {
    id: epic.name || id,
    title: epic.title || epic.name || id,
    methodology: epic.methodology || null,
    stories,
    docs,
    docs_path: path.relative(REPO_ROOT, docsDir),
  };
}

/**
 * One story's full YAML content. Returns null if the epic/story id doesn't
 * exist or the story yaml is malformed/unreadable (caller turns that into a
 * 404, never a 500).
 * @param {string} epicId
 * @param {string} storyId
 * @param {string} [root]
 */
export function getStory(epicId, storyId, root = DEFAULT_PHIVE_ROOT) {
  const storyPath = path.join(root, 'epics', epicId, 'stories', `${storyId}.yaml`);
  try {
    return readStoryYaml(storyPath);
  } catch (e) {
    process.stderr.write(`getStory(${epicId}, ${storyId}): ${e.message}\n`);
    return null;
  }
}

// Recent git log entries, via execFileSync — matches the router's
// established synchronous-CLI-wrapper convention (cli-runner.mjs's
// makeRun()/backlog.mjs's run()), not a new async pattern. Degrades
// gracefully to [] on any failure (e.g. cwd isn't a git repo), same
// read-degrades convention as backlog.mjs's getIssueRuns/getIssuePullRequests.
function gitLog(cwd, limit = 30) {
  try {
    const out = execFileSync('git', [
      'log', '-n', String(limit),
      '--pretty=format:%H%x1f%ad%x1f%s',
      '--date=iso-strict',
    ], {
      cwd,
      encoding: 'utf8',
      maxBuffer: 8 * 1024 * 1024,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    if (!out.trim()) return [];
    return out.split('\n')
      .map((line) => {
        const [hash, date, subject] = line.split('\x1f');
        return { type: 'commit', hash, date, subject, time: Date.parse(date) || 0 };
      })
      .filter((c) => c.hash);
  } catch (e) {
    process.stderr.write(`gitLog failed: ${e.message}\n`);
    return [];
  }
}

/**
 * Recent git log entries merged with .pHive/audits/post-run/*.yaml records,
 * sorted by time (most recent first). One malformed audit-record file is
 * skipped (with a stderr log) rather than aborting the whole merge.
 * @param {string} [root] .pHive root — overridable for tests
 * @param {string} [cwd] git working directory — overridable for tests
 */
export function listActivity(root = DEFAULT_PHIVE_ROOT, cwd = REPO_ROOT) {
  const commits = gitLog(cwd);

  const auditDir = path.join(root, 'audits', 'post-run');
  let files = [];
  try {
    files = fs.readdirSync(auditDir).filter((f) => f.endsWith('.yaml'));
  } catch (e) {
    files = [];
  }

  const audits = [];
  for (const f of files) {
    try {
      const raw = fs.readFileSync(path.join(auditDir, f), 'utf8');
      const parsed = parseYaml(raw);
      if (!parsed || typeof parsed !== 'object') throw new Error('empty or invalid audit record');
      audits.push({
        type: 'audit',
        file: f,
        ...parsed,
        time: Date.parse(parsed.timestamp) || 0,
      });
    } catch (e) {
      process.stderr.write(`listActivity: skipping malformed audit file ${f}: ${e.message}\n`);
    }
  }

  return [...commits, ...audits].sort((a, b) => (b.time || 0) - (a.time || 0));
}
